name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github-packages # Value of the distributionManagement/repository/id field of the pom.xml
          server-password: ${{ secrets.TOKEN }} # env variable for token in deploy
      - name: Publish package
        run: mvn -pl '!build-tools' -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true -Dcpd.skip=true -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
