name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: mvn -pl '!build-tools' -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true -Dcpd.skip=true -B package deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
